export const CHANGE_MESSAGE_TYPE = 'CHANGE_MESSAGE_TYPE';
export const CHANGE_MESSAGE_CONTENT = 'CHANGE_MESSAGE_CONTENT';
export const SHOW_TOAST_MESSAGE_TRUE = 'SHOW_TOAST_MESSAGE_TRUE';
export const SHOW_TOAST_MESSAGE_FALSE = 'SHOW_TOAST_MESSAGE_FALSE';
export const GOOGLE_BUTTON_LOADING_TRUE = 'GOOGLE_BUTTON_LOADING_TRUE';
export const GOOGLE_BUTTON_LOADING_FALSE = 'GOOGLE_BUTTON_LOADING_FALSE';